spring.application.name=configserver
server.port=8200
spring.cloud.config.server.git.uri=git@github.com:rohithVR101/HarlequinsCC.git
spring.cloud.config.server.git.default-label=master
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.ignore-local-ssh-settings=true
spring.cloud.config.server.git.privateKey= \
-----BEGIN RSA PRIVATE KEY-----\n\
MIIJKAIBAAKCAgEAvFv5eYTHBpUgxC2ETvnXRZ4by1KUKSyXwDKpx0ZrEoUh6W/T\n\
fWJwamWua98LH02IVpslBUcvDxVHZ6p8yJK3QhrniR8c9HxG6bpfFZhi2jpVksZq\n\
OWvRqhwcjau1hp94BxxBy4YO2W3Eyq9P00ONh/2ekW1/UwPbOzeUwnBAhZrNolTu\n\
4w6Q8rZ8sYnKqELXASOsQSst+ApzmGxzww+KpZWTCDY51vfscQa70tKz4fGPRdso\n\
i4N4CWxwFfD7rux3Lnp8lgesYVHiu0Tm+luVcla3mL0lUadhgAQLm4wmdP51LjCg\n\
yCrx8almCI4F240gCgCdpEiRhjMdwGxJaP4yC7zyZR5iRE6NasBVF5cmXVrGCb4C\n\
jqLrHZgJrQkKqpVuGUfgFmY8ndpAigDTo0KJ+WFtXHpQbj99KKHTpFJ8QzBqf88p\n\
uKoEcqy1n9qWYVLYSiudT8suCC8TYqBMU6j9gp4TDvwnMVCaZgbzjSP8qytbWAko\n\
EmUT5UvaCZc6rg+c2YtfX67S2ayZwqLsFnUQzJ0y1tnzTlCcEdH8D8MQf0kNnH4/\n\
6aI3vaCJiJF+BKvSYLKWITo2TUUjGyQ1xV/OJCLmPcVgsZSSDBpUq+1p7TyhgLWr\n\
cT3dhoebyKPFtddBC9pFroVOLstRe/5Fugw9/cuT5J8AjV21luRlsWNbpTkCAwEA\n\
AQKCAgBy4hYTC+zoEuTdQnXERZYLHBgPttovEserrjrnFAgST6kTW+U+QGAYRNRR\n\
bsS13vAdAptd0MDfDjdy/wUEwJeNdiNp+tQKOhJ2U/nSjhMczx+KWgJH638Bpgu0\n\
TNp2taTbkVx/6c/8xXqVtL+XN0iHfSTNxl82HtAEGi5dOWHhGz34mJzrV+MIZk0/\n\
a69zWPER/NP/G3r6IkXG3b7tZflGbSg0hf5ZIvXPKjA8sc6NLGwaS0U7coAwHzdt\n\
6oFXe1plusdqKlv1L6B+X9QRNvK7vjBUtGiimNha4BzEToLWMKz/8yDddXQD1TIq\n\
XZUtB7JW53E+1hQMKfknd+R+aSvT+B20R7TAopufjgOia0YU7As+urpmYEPyieYM\n\
sv8K3rJn+5Lc9rwo0E1qjxXfvzEX2QITtYE/39O13uU6VmkGQL2chjNBw2exstcY\n\
cli5QK6nsh2qJEwmzOPnhD6UUt2sAre1yaxxoN/pPjSoaCekwFGjd908wQPkyBLU\n\
+hF4icRtNw2QHEr4GmXb3Nbnqf+FTdxhhMS4JbQxBfEMvT6MIG9gLw7DzZXwCqCl\n\
l9DszlsJwu4YSczZkxCWtH0p+TYQJDSopB6z/LhbhnOZdHcVeNeDsftZOZ33Tlug\n\
s4w8/MTYZV/KehTSdVZ30+we3l1QMkW/6XPl/FoI9wS0iQmsAQKCAQEA7y8lVjeW\n\
yoQHa69rmhXQ9OCF18AjvtH9dVNc6xSwlg9Cr8NIjqmOCFHJh2FCyZMlD4jWnEXA\n\
jChWNLFVj9LNAPOwAO0Q7HaG48eXTSqvRKFjyUlzACl4fK50yn3jPMjIOuHivJcg\n\
3E5+zfVCUrU22Nw/Ck1+0/I0a/xkgid9rRuE2PdIXVukOd1yGgpZq42oSFLwm3c+\n\
SGKzVN0IbpJP+GLjRTljesSCgI1WwjyxPGvvegPaDkV2O5gnLJ+u/SOStCfFArlr\n\
BOB1AxPpG8x9xNDmt+MsKQRiJq6HlyO6anF8H642BPVDd740K8ko9DucMGy99ENJ\n\
jEDjPjX0N0SmIQKCAQEAyZoUHrKNmZRnFgQ5j2qrysDWlN0xq0nOqKOR0gFdVS6v\n\
XEbDRvrKrJ5evSBoLTtwusKZpaaHeL7rqzzXBkWStmUGWO8PCl+LpnFoH6p81owa\n\
ToQmj2PkNChJ7kITKgWmRl+qiSylQqop5H5DQUfIF9d7GkKvCmCLuor+owirQNZJ\n\
U2xSyoq6I+waaY8XPQDNZqsURas+t9U2DMyFj37eI23GRbaNWboa+IdzxdZXaRlh\n\
/cd3QdY6GjTJ3rZMjVh0Nq/WpSVQrx/s0Olniqzr/01BRFCJZfWzP2zjf3jPiPqR\n\
BWujrmMjKOPQ3ONG3Ns4fe+ffHl7xCJolPXlgmHsGQKCAQEA3Z5dhglz2qmDBrA/\n\
j0HvnzX6TfJmLIT9yBw52EgPZrs1Gw5iyG0qgWLmzF2+OG/ywvYThDDNPBCT77bw\n\
hJbaBKvGxNTj/XXFfoCNHJ8UTw8LGpLHz7qdPUmYRZdnWgbgIE70e7G8bOT+cW9y\n\
yJfH/h/0+WLcxR2CnRv7NO3KcP8ylKZrkrU68bLR6nb0pxRWfMz8y9AtEX0ClPtI\n\
uMsw9gEKfDW0iyhRkzNi1A7QWh/YgMHY5ahO6OEOSzaaOUsgv3SqAuAy3Q3s3bEx\n\
KOTNE/RMEs6XOForZ5QHZm9gZwhH7kLJIsbugKDoTjnRjJs/GU9ook9GcoIdDKOJ\n\
aTxegQKCAQA8mBUIDP7GdHZvhaGPW6566G8Wm008gJie01sW1dYprjiC8bnr8aFN\n\
NOSgz8bAIaeGWss3oNADGM9YzpaKigrIy6CWxnOs2H7u7hMvwVx4V+/oPYwheRK0\n\
Io/mDvIXpU8Ow95MEKEzYlXpGZI5YsvfbqLPh894vQACd5iFhCuE92NesaZIvl2o\n\
QmTF6X5Alacm/rC/J/NX6buvKSHTuXwnBe2cMnxVxbwpivzfL8diDYEIeBV+MleQ\n\
XOF4ES79JOL5NOy9AnQ3zs6tFBpM8iCUwbGmSNajULAplh7ix3sJXtaL3Ih798wv\n\
lBnI6n74DuPx5j33ecQbdYQdkbMD906xAoIBAEpI7FxK6x0VB2JqtrLVfaSja8ku\n\
W5l909St6Wt2Foo0xP2K8+6KtAhH8g0VqDsa/CZNXt2CayQbnWYr3HLNKOqWShnx\n\
Ho9kW0yvjUbuoP0bkFchBDd1mPlgbcVdCFU8AFCa0Qtcgw7PEVqkoSJaGiWhu8NY\n\
SvT3UeYAvdmPLrl4BKefRaM2hFCoUvV6cKrzbrdw6M+4BhrI+1aFXclTLGueIpqT\n\
LvinwmtRTarJ+efOB5U1cK5hQTKx1bI3ZAcpNf0I/a108j2dE2e0YMotBWLsEp6h\n\
cQeGHybaVrioIRBIvFCNIG3/OQtruVb0Kv3kzApyeoVcyukWMR3W3P3tZZY=\n\
-----END RSA PRIVATE KEY-----\n
spring.rabbitmq.host=localhost
spring.rabbitmq.username=guest
spring.rabbitmq.password=quins123
spring.rabbitmq.port=5672
management.endpoints.web.exposure.include=busrefresh